function option = fun_get_default_grape()
% option  = struct('Dynamics','@fun_taylor',...
%                  'Gradient','cdiff',...
%                  'CoopPulse','off',...
%                  'Constraint','@fun_constr_1rf_2component_max_amp');
option  = struct('Dynamics','@fun_taylor',...
                 'Gradient','cdiff',...
                 'Constraint','@fun_constr_1rf_2component_max_amp',...
                 'Cost','@fun_cost_distance_to_target');