function ListParameter = fun_get_list_field()
% ListParameter    = {'Dynamics',...
%                     'Gradient',...
%                     'CoopPulse',...
%                     'Constraint',...
%                     'Cost'};
ListParameter    = {'Dynamics',...
                    'Gradient',...
                    'Constraint',...
                    'Cost'};