function [u, fval, exitflag,output] = fun_interface_opt(u_ini,opt)
%---- set the option of fmincon
options = optimset(...
    'TolX',1e-8,...
    'TolFun',1e-8,...
    'Tolcon',1e-12,...
    'Display',opt.disp,...
    'MaxIter',opt.iter,...
    'MaxFunEvals',Inf,...
    'Algorithm','interior-point'...
    ,'Hessian',{'lbfgs',5},...
    'GradObj','on',...
    'Gradconstr','on',...
    'DerivativeCheck','off',...
    'LargeScale','on',...
    'AlwaysHonorConstraints','bounds',...
    'InitBarrierParam',1e-1);
%---- call fmincon
[u, fval, exitflag,output] = fmincon(str2func(opt.Cost),u_ini,[],[],[],[],[],[],...
                                     str2func(opt.Constraint),options,opt);