function gr  = fun_grad_rotation_exact(u,yin,pin,opt)
N               = opt.N;
M               = size(opt.par(:,1),1);
gr              = zeros(1,length(u));
grtmp           = zeros(3*M,1);
p               = reshape(pin(:),3,M).';
p2              = zeros(M,3);
for i1 = 1:N
    m            = sqrt(u(N-i1+1).^2+u(2*N-i1+1).^2);
    mm           = sqrt(opt.par(:,2).^2.*m.^2+opt.par(:,1).^2);
    chi          = mm * opt.dt;
    %----
    ct          = opt.par(:,1)./mm;
    st          = opt.par(:,2)*m./mm;
    cp          = u(N-i1+1)./m;
    sp          = u(2*N-i1+1)./m;
    cc          = cos(chi);
    sc          = sin(chi);
    %----
    p2(:,1) = (-st.^2 .* (cc - 0.1e1) .* cp .^ 2 + cc) .* p(:,1) + ...
              ( (1.0 - cc) .* st .^ 2 .* sp.*cp + ct .* sc) .*  p(:,2) + ...
              - st .*( (cc - 0.1e1) .* cp .* ct  + sc .* sp) .*  p(:,3);

    p2(:,2) = ( (- cc + 1).*st .^ 2 .* sp.*cp - ct .* sc) .*  p(:,1) + ...
              ( (cc - 0.1e1) .*( sp .^ 2 .* ct .^ 2 + cp .^ 2)+ 0.1e1) .*  p(:,2) + ...
              st .*( sc .* cp + (- cc + 1.0 ) .*sp .* ct) .*  p(:,3);

    p2(:,3) = st .*(- (cc - 0.1e1) .* cp .* ct +  sc .* sp) .*  p(:,1) + ...
              (-(cc - 0.1e1) .* ct .^ 2 + cc) .*  p(:,3) + ...
               -st .* ( (cc - 0.1e1) .* sp .* ct + sc .* cp) .*  p(:,2);
    %----
    ytmp        = reshape(yin(:,N-i1+1),3,M).';
    %----
    xpx     = ytmp(:,1) .* p(:,1);
    ypx     = ytmp(:,2) .* p(:,1);
    zpx     = ytmp(:,3) .* p(:,1);
    xpy     = ytmp(:,1) .* p(:,2);
    ypy     = ytmp(:,2) .* p(:,2);
    zpy     = ytmp(:,3) .* p(:,2);
    xpz     = ytmp(:,1) .* p(:,3);
    ypz     = ytmp(:,2) .* p(:,3);
    zpz     = ytmp(:,3) .* p(:,3);
    %----
    grtmp(1:M)       = - 2.0 * st.^2 .* (cc - 1.0) .* (ypx + xpy) .* cp .^ 2 ...
                     + cp .* (-2 .* sp .* (cc - 1.0) .* (xpx - ypy) .* ct .^ 2 ...
                     - st .* ( (cc - 1.0) .* (zpy + ypz) .* ct  + sc .* (-zpx + xpz)) ...
                     + 2 * sp .* ( (xpx - ypy) .* cc - xpx +  ypy ))...
                     + (cc - 1) .* ct .* ( - (ypx + xpy) .* ct + sp .* st .* (zpx + xpz) ) ...
                     + (ypx + xpy) .* cc ...
                     - sc .* st .* (-zpy + ypz) .* sp - (xpy + ypx);
    grtmp((1:M)+M)   = -2.0 * (cc - 1.0) .* ((zpx + xpz) .* cp + sp .* (zpy + ypz)) .* ct .^ 2 ...
                     + ct .* (-2.0 * st .* (cc - 1.0) .* ( (xpx - ypy) .* cp .^ 2 + (ypy - zpz) ) - sc .* sp .* (-zpx + xpz) ...
                     + (-2.0 * sp .* (cc - 1.0) .* (ypx + xpy) .* st + sc .* (-zpy + ypz)) .* cp ) ...
                     + (cc - 1.0) .* (zpx + xpz) .* cp ...
                     - sc .* (-ypx + xpy) .* st ...
                     + sp .* (cc - 1.0) .* (zpy + ypz);
    grtmp((1:M)+2*M) = (((-xpx + ypy) .* cp .^ 2 ...
                     - sp .* (ypx + xpy) .* cp - ypy + zpz) .* ct .^ 2 ...
                     + ((zpx + xpz) .* cp ...
                     + sp .* (zpy + ypz)) .* st .* ct ...
                     + (xpx - ypy) .* cp .^ 2 ...
                     + sp .* (ypx + xpy) .* cp ...
                     - (xpx + zpz)) .* sc ...
                     + cc .* ((-ypx + xpy) .* ct - st .* ((-ypz + zpy) .* cp + sp .* (-zpx + xpz)));
    %---- grad of spherical angle to grad of u !
    gr(N-i1+1) = sum(u(N-i1+1).*opt.par(:,2).*opt.par(:,1) ./(mm.^2.*m ) .* grtmp(M+(1:M)) ...
                        -u(2*N-i1+1) / m^2 .* grtmp((1:M)) ...
                     + opt.dt ./mm .* u(N-i1+1) .* opt.par(:,2).^2 .* grtmp(2*M+(1:M)));
    %
    gr(2*N-i1+1) = sum(u(2*N-i1+1).*opt.par(:,2).*opt.par(:,1) ./(mm.^2.*m) .* grtmp(M+(1:M)) ...
                           +  u(N-i1+1) / m^2 .* grtmp((1:M)) ...
                     + opt.dt ./mm .* u(2*N-i1+1) .* opt.par(:,2).^2 .* grtmp(2*M+(1:M)));
    %----
    p               = p2;
end